name: Check Memoise Function

#Que lo inicia o enciende y a que rama afecta
on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      #Comprovamos que haya un repositorio
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
        # Permite configurar que version de Node queremos
      - uses: actions/setup-node@v4
        with:
          cache: "npm"
          node-version: "18"
        # Instalamos todas las dependencia de modo claro
      - name: Install dependencies
        run: npm ci

      # Compilamos TSC y vite con build
      - name: Build project
        run: npm run build

        # Ejecutamos el Lint para comprovar que cumple con las reglas de estilos
      - name: Ejecutar esLint
        run: npm run lint

        # Ejecutamos que el test sea correcto
      - name: Test
        run: npm test
